spring:
  application:
    name: GREET-API
server:
  port: 2222
#Manual process to add to eureka server
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:9191}/eureka/
