spring:
  application:
    name: Admin-Client2-API
  boot:
    admin:
      client:
        url: http://localhost:9090/
server:
  port: 1313
management:
  endpoints:
    web:
      exposure:
        include: '*'

